imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:
        paths:
            - '%kernel.root_dir%/Resources/translations'
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    ide: 'phpstorm://open?file=%%f&line=%%l'


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: %kernel.debug%

    clients:
        api_bandsintown:
            base_url: "http://api.bandsintown.com"
            headers:
                Accept: "application/json"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            suggest_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, elision]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                artist:
                    _source:
                        excludes: [suggest]
                    mappings:
                        name:
                            type: text
                            boost: 6
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                        suggest:
                            type: completion
                            analyzer: suggest_analyzer
                            search_analyzer: suggest_analyzer
                            contexts:
                                - {type: category, name: genre}
                        biography:
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                        creationYear:
                            type: date
                            format: "yyyy"
                            fields:
                                raw:
                                    type: integer
                        genres:
                            property_path: genreLabels
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                            fields:
                                raw:
                                    type: keyword
                        albumCount:
                            type: integer
                        albums:
                            type: nested
                            include_in_all: false
                            properties:
                                title:
                                    type: text
                                    analyzer: custom_analyzer
                                    search_analyzer: custom_search_analyzer
                                releaseDate:
                                    type: date
                                    format: "dateOptionalTime"
                                tracks:
                                    type: nested
                                    include_in_all: false
                                    properties:
                                        number:
                                            type: integer
                                        title:
                                            type: text
                                            analyzer: custom_analyzer
                                            search_analyzer: custom_search_analyzer
                                        lyrics:
                                            type: text
                                            analyzer: custom_analyzer
                                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Artist
                        provider: ~
                        listener: ~
                        finder: ~
                album:
                    mappings:
                        title:
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                        releaseDate:
                            type: date
                            format: "dateOptionalTime"
                        artist:
                            type: object
                            properties:
                                name:
                                    type: text
                                    analyzer: custom_analyzer
                                    search_analyzer: custom_search_analyzer
                                genres:
                                    type: nested
                                    properties:
                                        label:
                                            type: text
                                            analyzer: custom_analyzer
                                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Album
                        provider: ~
                        listener: ~
                        finder: ~
                genre:
                    mappings:
                        label:
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Genre
                        provider: ~
                        listener: ~
                        finder: ~
                track:
                    mappings:
                        number:
                            type: integer
                        title:
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                        lyrics:
                            type: text
                            analyzer: custom_analyzer
                            search_analyzer: custom_search_analyzer
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Track
                        provider: ~
                        listener: ~
                        finder: ~
