# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    fos_user.doctrine_registry:
#        alias: doctrine

    app.bandsintown.client:
        class: AppBundle\Client\BandsInTownClient
        arguments: [ "%bandsintown_app_id%", "@guzzle.client.api_bandsintown" ]

    app.artist.listener:
        class: AppBundle\EventListener\ArtistShowListener
        arguments: []
        tags:
            - {name: kernel.event_listener, event: 'app.artist.show', method: 'onShow'}

    app.artist.view_count.listener:
        class: AppBundle\EventListener\IncrementViewCountListener
        arguments: ['@request_stack']
        tags:
            - {name: kernel.event_listener, event: 'app.artist.show', method: 'onShow'}

    app.artist.subscriber:
        class: AppBundle\EventListener\ArtistEventSubscriber
        arguments: ['@mailer', '@security.token_storage']
        tags:
            - {name: kernel.event_subscriber}

    app.artist_voter:
        class: AppBundle\Security\ArtistVoter
        tags:
            - { name: security.voter }
        public: false

    any.name_order_filter:
        parent:    'api_platform.doctrine.orm.order_filter'
        arguments: [ { name: 'ASC' } ]
        tags:      [ { name: 'api_platform.filter', id: 'name.order' } ]

    album.artist_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { artist.id: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'album.artist' } ]

    album.order_filter:
        parent:    'api_platform.doctrine.orm.order_filter'
        arguments: [ { releaseDate: 'ASC' } ]
        tags:      [ { name: 'api_platform.filter', id: 'album.order' } ]

    artist.genre_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { genres.id: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'artist.genre' } ]

    genre.label_order_filter:
        parent:    'api_platform.doctrine.orm.order_filter'
        arguments: [ { label: 'ASC' } ]
        tags:      [ { name: 'api_platform.filter', id: 'label.order' } ]

    genre.label_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { label: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'label.filter' } ]

    any.name_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'name.filter' } ]

