# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.bandsintown.client:
        class: AppBundle\Client\BandsInTownClient
        arguments: [ "%bandsintown_app_id%", "@guzzle.client.api_bandsintown" ]

    app.artist.listener:
        class: AppBundle\EventListener\ArtistShowListener
        arguments: []
        tags:
            - {name: kernel.event_listener, event: 'app.artist.show', method: 'onShow'}

    app.artist.view_count.listener:
        class: AppBundle\EventListener\IncrementViewCountListener
        arguments: ['@request_stack']
        tags:
            - {name: kernel.event_listener, event: 'app.artist.show', method: 'onShow'}

    app.artist.subscriber:
        class: AppBundle\EventListener\ArtistEventSubscriber
        arguments: ['@mailer', '@security.token_storage']
        tags:
            - {name: kernel.event_subscriber}

    app.artist_voter:
        class: AppBundle\Security\ArtistVoter
        tags:
            - { name: security.voter }
        public: false
